### ISSUE TITLE
Corrigir

### ISSUE THREAD

**Issue by Henry12960** [Estem01/MultiProtocol#11]
Remova de if:

: void {

Deixe:

if ($pk instanceof LoginPacket) {

**Comment by Estem01** [comment]
Ok :) só tem um problema que é 
$this->acceptProtocol[] = ProtocolInfo::CURRENT_PROTOCOL;

Esse ; tá dando erro e eu não sei o porquê.........

**Comment by Estem01** [comment]
@Henry12960

**Comment by Henry12960** [comment]
Não sei mexer com as packages do pocketmine kkkkk

**Comment by Estem01** [comment]
Já arrumei o problema
