### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZippingBoat9588** [Estem01/MultiProtocol#4]
![Screenshot_20220618-145939](https://user-images.githubusercontent.com/104681534/174438812-ae18484b-bbfb-47b8-861c-08b41b7fd73d.png)

**Comment by SayakaPM** [comment]
You are using latest release

**Comment by ZippingBoat9588** [comment]
Can you Update to 4.5.0 ? Pls i need it

**Comment by Estem01** [comment]
Yes I will update to version 4.5.0 :)

**Comment by Estem01** [comment]
I've updated to the latest version :)
