### ISSUE TITLE
Corrigir

### ISSUE THREAD

**Issue by Henry12960** [Estem01/MultiProtocol#5]
Se você quiser esse plugin na API 4 deve fazer as seguintes trocas:

1. Plugin.yml 

--> Mudar para somente API 4 - Ex: [4.0.0]

2. MultiProtocol.php

--> Mudar para public function onEnable() : void {

--> Mudar para $player = $event->getServer->getPlayer(); (Isso é variável, pode ser que não funcione)

**Comment by Estem01** [comment]
Valeu Henry :)

**Comment by Estem01** [comment]
Bem infelizmente a variável não foi mais vou tentar de outra forma 😁
