### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ZippingBoat9588** [Estem01/MultiProtocol#7]
![Screenshot_20220618-213457](https://user-images.githubusercontent.com/104681534/174454730-8cf60aa6-bf5f-4ebe-850b-a60418d283ad.png)

**Comment by Henry12960** [comment]
The plugin is not ready yet, wait a while until it is fixed!

**Comment by Estem01** [comment]
you can now test that it's working :) @ZippingBoat9588

**Comment by ZippingBoat9588** [comment]
ITS say the Same bot working! :(

**Comment by ZippingBoat9588** [comment]
![Screenshot_20220618-235511](https://user-images.githubusercontent.com/104681534/174458206-758bb428-4e13-42fa-ab5e-bc6681767924.png)

**Comment by Estem01** [comment]
which version are you using?

**Comment by SiahRBLX** [comment]
New Issue @Estem01 

[21:54:38.622] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[21:54:38.622] [Server thread/CRITICAL]: Could not load plugin 'MultiProtocol': Multiple minimum API versions found for some major versions (4.5.1, 4.5.0, 4.4.0, 4.3.0, 4.2.0, 4.1.0, 4.0.0)

[21:54:38.622] [Server thread/EMERGENCY]: Failed to load some plugins, stopping server to protect server integrity
[21:54:38.622] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by ZippingBoat9588** [comment]
@Estem01 Pocketmine 4.5.0 Plugin Last devs

**Comment by Estem01** [comment]
I switched to 4.5.0 just for this one to see if it works

**Comment by Estem01** [comment]
@ZippingBoat9588 @SiahRBLX

**Comment by ZippingBoat9588** [comment]
![Screenshot_20220619-000000](https://user-images.githubusercontent.com/104681534/174458297-4168b1fe-9510-43cb-895c-53e62bd73df9.png)

**Comment by ZippingBoat9588** [comment]
@Estem01 Dev 45 Work 4.5.0

**Comment by ZippingBoat9588** [comment]
Wich Version of MC can i nie use older

**Comment by Estem01** [comment]
@ZippingBoat9588 try using official 4.5.0 without dev version

**Comment by ZippingBoat9588** [comment]
@Estem01 where i can find it?

**Comment by Estem01** [comment]
@ZippingBoat9588 On pocketmine's github in release versions more I'll add this dev45 in plugin versions :)

**Comment by ZippingBoat9588** [comment]
It Says i lost Connection 2 Times but i have good Connect!?
![Screenshot_20220619-001711](https://user-images.githubusercontent.com/104681534/174458765-713be099-f3e7-49cb-9c25-f00256c87299.png)
@Estem01

**Comment by Estem01** [comment]
@ZippingBoat9588 this MultiProtocol server only for versions of 1.19, that is, I am on 1.9.10 and the server is on 1.19.30, I will be able to enter more if your mine is 1.18.300 it will not work!

**Comment by ZippingBoat9588** [comment]
Uhh okay will it anywehre Support older Version Like 1.17?

**Comment by Estem01** [comment]
no :/ unfortunately this is not a multiversion but I can make a version for 1.17 :) more that will only work in pm of 1.17 or versions of 1.17 @ZippingBoat9588

**Comment by ZippingBoat9588** [comment]
Nah i Just think but thanks for all

**Comment by Estem01** [comment]
Well I will make this plugin both in pm4 pm4 and pm2 :) you're welcome

**Comment by Estem01** [comment]
the plugin is already stable
